# Generated by Django 4.2.17 on 2025-01-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Clinician', 'Clinician'), ('Analyst', 'Analyst')], default='Clinician', max_length=10),
        ),
    ]
